version: '3.8'

services:
  frontend:
    image: ghcr.io/goldkach/investment-platform-frontend:v11
    container_name: goldkach-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  api:
    image: ghcr.io/goldkach/investment-api:v8
    container_name: goldkach-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CRON_MODE=daily
    networks:
      - app-network

networks:
  app-network:
    driver: bridge